export const cluesJson = [{"clue": "I WRITE MY JOKES IN ________. THIS ONE WAS WRITTEN IN PARIS", "answer": "CAPITALS", "start": [20, 21], "end": [27, 21]},
 {"clue": "What time did the man go to the dentist? ___________", "answer": "TOOTHHURTY", "start": [29, 17], "end": [29, 26]},
 {"clue": "I'm reading a book about anti-gravity. It's impossible to _______", "answer": "PUTDOWN", "start": [12, 7], "end": [18, 7]},
 {"clue": "How does a Jewish person make tea? _______ it", "answer": "HEBREWS", "start": [18, 13], "end": [18, 19]},
 {"clue": "What kind of doctor is Dr. Pepper? He's a _________", "answer": "FIZZICIAN", "start": [3, 13], "end": [3, 21]},
 {"clue": "What's the difference between a hot potato and a flying pig? One's a heated yam, the other's a _________", "answer": "YEETEDHAM", "start": [24, 7], "end": [32, 7]},
 {"clue": "Two peanuts were walking. One was _______", "answer": "ASALTED", "start": [21, 13], "end": [27, 13]},
 {"clue": "What kind of bees produce milk? _______", "answer": "BOOBEES", "start": [27, 15], "end": [27, 21]},
 {"clue": "What do you call a witch at the beach? A ________", "answer": "SANDWICH", "start": [14, 18], "end": [21, 18]},
 {"clue": "Why was the river rich? Because it had two _____", "answer": "BANKS", "start": [27, 15], "end": [31, 15]},
 {"clue": "Why didn't the skeleton go for prom? Because it had ______", "answer": "NOBODY", "start": [13, 24], "end": [13, 29]},
 {"clue": "What did the customer say to the waiter? I'm all _____ with your service", "answer": "FEDUP", "start": [9, 16], "end": [9, 20]},
 {"clue": "To whoever stole my copy of Microsoft Office, I will find you. You have my ____", "answer": "WORD", "start": [11, 23], "end": [11, 26]},
 {"clue": "Why did the koala get rejected? Because he did not have any ______________", "answer": "KOALAFICATIONS", "start": [22, 0], "end": [22, 13]},
 {"clue": "What's the best thing about Switzerland? I don't know, but the flag is a _______", "answer": "BIGPLUS", "start": [21, 10], "end": [27, 10]},
 {"clue": "What do you call a cow with no legs? __________", "answer": "GROUNDBEEF", "start": [9, 24], "end": [18, 24]},
 {"clue": "____________ cat walks into a bar and doesn't", "answer": "SCHRODINGERS", "start": [5, 9], "end": [16, 9]},
 {"clue": "The past, the present and the future walk into a bar. It was _____", "answer": "TENSE", "start": [27, 7], "end": [27, 11]},
 {"clue": "What did the cell say when his sister cell stepped on his foot? _______", "answer": "MITOSIS", "start": [5, 13], "end": [11, 13]},
 {"clue": "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and _____", "answer": "RIGHT", "start": [26, 3], "end": [30, 3]},
 {"clue": "How do you make holy water? You boil the ____ out of it", "answer": "HELL", "start": [13, 31], "end": [13, 34]},
 {"clue": "What do you call a deer with no eyes? _________", "answer": "NOEYEDEER", "start": [16, 18], "end": [16, 26]},
 {"clue": "Where do sick cruise ships go to get healthy? The ____", "answer": "DOCK", "start": [1, 18], "end": [1, 21]},
 {"clue": "How do construction workers party? They raise the ____", "answer": "ROOF", "start": [13, 11], "end": [16, 11]},
 {"clue": "I was struggling to figure out how lightning works, but then it ______ me", "answer": "STRUCK", "start": [8, 25], "end": [8, 30]},
 {"clue": "How much did your chimney cost? Nothing, it was __________", "answer": "ONTHEHOUSE", "start": [9, 3], "end": [18, 3]},
 {"clue": "What does Santa suffer from if he gets stuck in a chimney? ______________", "answer": "CLAUSTROPHOBIA", "start": [1, 20], "end": [14, 20]},
 {"clue": "Who is Santa's favourite singer? ____________", "answer": "ELFISPRESLEY", "start": [20, 5], "end": [31, 5]},
 {"clue": "Why are cats so good at video games? They have _________", "answer": "NINELIVES", "start": [2, 17], "end": [10, 17]},
 {"clue": "Why did the banana go see a doctor? Because it wasn't _______ well", "answer": "PEELING", "start": [24, 10], "end": [24, 16]},
 {"clue": "What's the difference between a poorly dressed man on a unicycle and a well dressed man on a bicycle? ______", "answer": "ATTIRE", "start": [27, 0], "end": [27, 5]},
 {"clue": "Why shouldn't you visit an expensive wig shop? It's too high a price ______", "answer": "TOUPEE", "start": [29, 20], "end": [34, 20]},
 {"clue": "You see, mountains aren't just funny. They are _________", "answer": "HILLAREAS", "start": [0, 25], "end": [8, 25]},
 {"clue": "Never date a baker. They're too ______", "answer": "KNEADY", "start": [25, 18], "end": [25, 23]},
 {"clue": "What does the mermaid wear to math class? ________", "answer": "ALGAEBRA", "start": [4, 25], "end": [4, 32]},
 {"clue": "Did you hear about the claustrophobic astronaut? He just needed a little _____", "answer": "SPACE", "start": [14, 18], "end": [14, 22]},
 {"clue": "Which is faster, Hot or cold? Hot, because you can _____ a cold", "answer": "CATCH", "start": [20, 18], "end": [20, 22]},
 {"clue": "I just saw my wife trip over and drop a basket full of ironed clothes. I watched it all ______", "answer": "UNFOLD", "start": [8, 28], "end": [13, 28]},
 {"clue": "I was feeling depressed, my wife put her hand on my back and said Earth. It meant ________ to me", "answer": "THEWORLD", "start": [14, 7], "end": [14, 14]},
 {"clue": "Which part of the hospital has the least privacy? The ___", "answer": "ICU", "start": [27, 28], "end": [27, 30]},
 {"clue": "A Roman walks into a bar and raises 2 fingers and says to the bartender... ____ beers, please", "answer": "FIVE", "start": [10, 28], "end": [10, 31]},
 {"clue": "I stayed up all night wondering where the sun went. Then it ______ on me", "answer": "DAWNED", "start": [14, 14], "end": [19, 14]},
 {"clue": "A perfectionist walked into a bar... apparently, the bar was not set __________", "answer": "HIGHENOUGH", "start": [23, 20], "end": [23, 29]},
 {"clue": "Whats the Grinchs least favorite band? ______", "answer": "THEWHO", "start": [30, 3], "end": [30, 8]},
 {"clue": "Why do ghosts go on diets? So they can keep their ________ figures.", "answer": "GHOULISH", "start": [9, 7], "end": [9, 14]},
 {"clue": "What is in a ghost's nose? _______", "answer": "BOOGERS", "start": [27, 18], "end": [33, 18]},
 {"clue": "What's it like to be kissed by a vampire? It's a _____________", "answer": "PAININTHENECK", "start": [16, 29], "end": [28, 29]},
 {"clue": "Why did the ghost go inside the bar? For the ____", "answer": "BOOS", "start": [22, 26], "end": [25, 26]},
 {"clue": "I can't believe I got fired from the calendar factory. All I did was take a ______", "answer": "DAYOFF", "start": [19, 1], "end": [24, 1]},
 {"clue": "I went to the zoo the other day. There was only a dog in it - it was a _______", "answer": "SHIHTZU", "start": [1, 23], "end": [1, 29]},
 {"clue": "What does a baby computer call his father? ____", "answer": "DATA", "start": [17, 28], "end": [17, 31]},
 {"clue": "I only seem to get sick on weekdays. I must have a _______ immune system", "answer": "WEEKEND", "start": [18, 2], "end": [18, 8]},
 {"clue": "I just found out I'm colorblind. The news came out of the ______", "answer": "PURPLE", "start": [27, 24], "end": [32, 24]},
 {"clue": "I hate my job-all I do is crush cans all day. It's ____________", "answer": "SODAPRESSING", "start": [13, 16], "end": [24, 16]},
 {"clue": "Papa tomato, Mama tomato and baby tomato are walking down the street. Baby tomato starts lagging behind and papa tomato gets really angry, goes back and says _______", "answer": "KETCHUP", "start": [9, 31], "end": [15, 31]},
 {"clue": "Why was Cinderella so bad at soccer? She kept running away from the ____", "answer": "BALL", "start": [20, 3], "end": [23, 3]}];
