export const cluesJson = [{"clue": "I WRITE MY JOKES IN ________. THIS ONE WAS WRITTEN IN PARIS", "answer": "CAPITALS", "start": [24, 6], "end": [24, 13]},
 {"clue": "What time did the man go to the dentist? ___________", "answer": "TOOTHHURTY", "start": [20, 11], "end": [20, 20]},
 {"clue": "I'm reading a book about anti-gravity. It's impossible to _______", "answer": "PUTDOWN", "start": [22, 10], "end": [28, 10]},
 {"clue": "What's the difference between a hot potato and a flying pig? One's a heated yam, the other's a _________", "answer": "YEETEDHAM", "start": [7, 1], "end": [7, 9]},
 {"clue": "Two peanuts were walking. One was _______", "answer": "ASALTED", "start": [12, 24], "end": [18, 24]},
 {"clue": "What kind of bees produce milk? _______", "answer": "BOOBEES", "start": [14, 9], "end": [20, 9]},
 {"clue": "What do you call a witch at the beach? A ________", "answer": "SANDWICH", "start": [0, 7], "end": [7, 7]},
 {"clue": "Why was the river rich? Because it had two _____", "answer": "BANKS", "start": [20, 5], "end": [20, 9]},
 {"clue": "Why didn't the skeleton go for prom? Because it had ______", "answer": "NOBODY", "start": [28, 10], "end": [28, 15]},
 {"clue": "What did the customer say to the waiter? I'm all _____ with your service", "answer": "FEDUP", "start": [22, 6], "end": [22, 10]},
 {"clue": "To whoever stole my copy of Microsoft Office, I will find you. You have my ____", "answer": "WORD", "start": [25, 18], "end": [25, 21]},
 {"clue": "Why did the koala get rejected? Because he did not have any ______________", "answer": "KOALAFICATIONS", "start": [2, 15], "end": [15, 15]},
 {"clue": "____________ cat walks into a bar and doesn't", "answer": "SCHRODINGERS", "start": [2, 0], "end": [2, 11]},
 {"clue": "The past, the present and the future walk into a bar. It was _____", "answer": "TENSE", "start": [18, 7], "end": [22, 7]},
 {"clue": "What did the cell say when his sister cell stepped on his foot? _______", "answer": "MITOSIS", "start": [22, 16], "end": [22, 22]},
 {"clue": "How do you make holy water? You boil the ____ out of it", "answer": "HELL", "start": [2, 2], "end": [5, 2]},
 {"clue": "What do you call a deer with no eyes? _________", "answer": "NOEYEDEER", "start": [2, 23], "end": [10, 23]},
 {"clue": "How do construction workers party? They raise the ____", "answer": "ROOF", "start": [18, 12], "end": [21, 12]},
 {"clue": "I was struggling to figure out how lightning works, but then it ______ me", "answer": "STRUCK", "start": [15, 15], "end": [15, 20]},
 {"clue": "How much did your chimney cost? Nothing, it was __________", "answer": "ONTHEHOUSE", "start": [11, 0], "end": [11, 9]},
 {"clue": "What does Santa suffer from if he gets stuck in a chimney? ______________", "answer": "CLAUSTROPHOBIA", "start": [15, 19], "end": [28, 19]},
 {"clue": "Why did Santa's helper see the doctor? Because he had a low _________", "answer": "ELFESTEEM", "start": [0, 3], "end": [0, 11]},
 {"clue": "What's the difference between a poorly dressed man on a unicycle and a well dressed man on a bicycle? ______", "answer": "ATTIRE", "start": [17, 19], "end": [17, 24]},
 {"clue": "Why shouldn't you visit an expensive wig shop? It's too high a price ______", "answer": "TOUPEE", "start": [7, 4], "end": [12, 4]},
 {"clue": "I was feeling depressed, my wife put her hand on my back and said Earth. It meant ________ to me", "answer": "THEWORLD", "start": [18, 7], "end": [18, 14]},
 {"clue": "A perfectionist walked into a bar... apparently, the bar was not set __________", "answer": "HIGHENOUGH", "start": [15, 3], "end": [15, 12]},
 {"clue": "Whats the Grinchs least favorite band? ______", "answer": "THEWHO", "start": [14, 3], "end": [19, 3]},
 {"clue": "Why do ghosts go on diets? So they can keep their ________ figures.", "answer": "GHOULISH", "start": [17, 17], "end": [24, 17]},
 {"clue": "What is in a ghost's nose? _______", "answer": "BOOGERS", "start": [13, 18], "end": [13, 24]},
 {"clue": "What's it like to be kissed by a vampire? It's a _____________", "answer": "PAININTHENECK", "start": [8, 13], "end": [8, 25]},
 {"clue": "What does a turkey dress up as for Halloween? A _______", "answer": "GOBBLIN", "start": [17, 1], "end": [23, 1]},
 {"clue": "Why did the ghost go inside the bar? For the ____", "answer": "BOOS", "start": [19, 1], "end": [19, 4]},
 {"clue": "I just got fired from my job at the keyboard factory. They told me I wasn't putting in enough ______", "answer": "SHIFTS", "start": [15, 22], "end": [20, 22]},
 {"clue": "I can't believe I got fired from the calendar factory. All I did was take a ______", "answer": "DAYOFF", "start": [8, 0], "end": [13, 0]},
 {"clue": "I went to the zoo the other day. There was only a dog in it - it was a _______", "answer": "SHIHTZU", "start": [11, 11], "end": [11, 17]},
 {"clue": "What does a baby computer call his father? ____", "answer": "DATA", "start": [6, 19], "end": [9, 19]},
 {"clue": "I just found out I'm colorblind. The news came out of the ______", "answer": "PURPLE", "start": [10, 7], "end": [15, 7]},
 {"clue": "I hate my job-all I do is crush cans all day. It's ____________", "answer": "SODAPRESSING", "start": [2, 21], "end": [13, 21]}];